# Generated by Django 2.0.1 on 2018-02-21 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bulkproduct',
            old_name='reoder_trigger',
            new_name='reorder_trigger',
        ),
    ]
