# Generated by Django 2.0.1 on 2018-02-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20180221_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalproduct',
            name='retire_date',
            field=models.DateTimeField(null=True),
        ),
    ]
